# Generated by Django 4.1.3 on 2022-12-08 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_customer_documents_alter_user_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="documents",
            field=models.FileField(blank=True, null=True, upload_to="files"),
        ),
    ]
